### ISSUE TITLE
Error while using MTA mysql

### ISSUE THREAD

**Issue by Dexter4002** [parkervcp/eggs#1045]
Panel Version: 1.31
Daemon Version: 1.3.1
Service: MTA
Modified: NO

Expected Behavior:
MTA Connect to database
Actual Behavior:
Get error: 
```
[08:51:43] MODULE: Unable to load x64/modules/mta_mysql.so (libmysqlclient.so.16: cannot open shared object file: No such file or directory)
To fix MODULE: Unable to find modules/mta_mysql.so (libmysqlclient.so.16: cannot open shared object file: No such file or directory)! copy libmysqlclient.so.16 into /usr/lib
```
Steps to Reproduce: (Step by step what to do to cause the issue)
Install mta script that uses database

**Comment by parkervcp** [comment]
As I said in #739 I am not really supporting this. If someone else wants to build out the support that's needed that's fine.

**Comment by BenasPaulikas** [comment]
@parkervcp I want to tacke this issue.

Do I understand correctly that I can't put files to /usr/lib manually for each server ? Because when I try it says it's read only system. Could you help understand this.

What other manual solutions could I do ? Symlink wouldn't work here I guess ?

**Comment by alanescarcha** [comment]
I see in some forums that there are many MTA servers that use the MTA-MySQL module [DEPRECATED] so I have created an image with libmysqlclient.so (64 bits) so that whoever sees this can solve this error by simply **changing the Docker image in the Egg and in the Startup of the server**: `ghcr.io/alanescarcha/mta_sa_ubuntu:latest`
