### ISSUE TITLE
Server never "starts"

### ISSUE THREAD

**Issue by Haxbi** [parkervcp/eggs#1126]
Panel Version: 1.4
Daemon Version: 1 4
Service: discord.py egg
Modified: No

Expected Behavior: once started for pterodactyl to say the server has "Started"

Actual Behavior:
Pteryodactyl always says server is "Starting"

Steps to Reproduce: Start server using bot script that listens for events. Assuming this is keeping it open.

**Comment by Software-Noob** [comment]
You have to edit the egg's start configuration to change your server status to "running", otherwise the Panel doesn't know when your bot is ready and running. Go to your admin panel, select the egg, and at the bottom, you will find "Start Configuration".

Edit the text to match something that your bot will print into the console when it has started for Pterodactyl to detect it as running. 
```
{
    "done": "change this text"
}
```

You can use arrays to have multiple different values
```
{
  "done":[
    "change this text 1",
    "change this text 2"
  ]
}
```

**Comment by Haxbi** [comment]
Sick. Thank you, I thought it might of been something like that. Will close now.
