### ISSUE TITLE
The Forest can not start

### ISSUE THREAD

**Issue by NgLoader** [parkervcp/eggs#136]
Panel Version: 0.7.11
Daemon Version: 0.6.8
Service: The Forest
Modified: yes

Hallo,

Im trying to run ``wine`` with ``xvfb`` for ``the forest``

The installing is success but on boot it says ``/usr/bin/xvfb-run: 184: /usr/bin/xvfb-run: 0: not found``
But it exists and I don't know why it's says that.

I'm simulated it with docker like pterodactyl and it's work's

Info:
You need to run the forest with VAC (When your installing the egg the config will be added and VAC is automaticly enabled) !
By the first time when your trying to start the forest it's able to crash (only first time setup)

Script:
[Pterodactyl Egg](https://gist.github.com/NgLoader/496b33e360d531826976a5a1e932b57d)
[Docker Image](https://quay.io/repository/ngloader/wine-steam)
[Docker Image Src](https://github.com/NgLoader/images/tree/ubuntu/steamcmd-wine)

**Comment by WolfPack30156** [comment]
Hello, I found your egg on your [gist](https://gist.github.com/NgLoader/496b33e360d531826976a5a1e932b57d) and ran into the same issue. 

The issue that I've found it to be is that the package `xvfb` isn't installed on the panel's host machine.  

After I logged into the server that was hosting Pterodactyl Panel and ran an update the grab the package the server ran; however, started to hang following some issues. I experimented with the launch options I found for some reason I had to wrap the command in quotations in order to launch escaping the double quotes used in the start up command. I haven't yet tried switching to only single quotes as this would not need escape characters for the quotes before Server.cfg and the save folder path.

Original Startup from your gist:
`xvfb-run --auto-servernum --server-args='-screen 0 640x480x24:32' wine ./TheForestDedicatedServer.exe -batchmode -nographics -savefolderpath "/games/data/forest/saves/" -configfilepath "Server.cfg"`

Startup I am using
`"xvfb-run --auto-servernum --server-args='-screen 0 640x480x24:32' wine ./TheForestDedicatedServer.exe -batchmode -nographics -savefolderpath \"/games/data/forest/saves\" -configfilepath \"Server.cfg\""`

After getting the server to take the arguments for `xvfb` and load `wine` I experienced some issues with errors. I added `winetricks` to the system and the errors went down considerably though I still experience the problem where I get what I believe to be a Unity Engine exception. [issue](https://github.com/WolfPack30156/add-the-forest-egg/issues/2) I mentioned in [my repo of the egg.](https://github.com/WolfPack30156/add-the-forest-egg)


I added `xvfb` to the install script of the egg; however, this might be wrong due to something @parkervcp [linked](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md#step-1) me on the discord. Which I believe is my misunderstanding of how the install works. 


I added a few changes to the egg as well including allowing Pterodactyl to see the panel configuration options [Ports, name, passwords, etc] can be set up for all the configuration switches needed. 


On a fresh install of the egg onto a server via the panel I still have the issue you mentioned 

> By the first time when your trying to start the forest it's able to crash (only first time setup)

I'm not sure why this occurs; however, my output was posted to the [issue](https://github.com/WolfPack30156/add-the-forest-egg/issues/1) I made for it on my repo.

I would like to say thank you for your gist post as without it I wouldn't have been able to experiment with making an egg. I learned a lot from this process and am aware of more I need to research to further understand the mechanics of both Pterodactyl and eggs. Hope this helps you. 

Kind Regards
-Wolfy

My version information is below:

Panel Version: 0.7.13
Daemon Version: 0.6.12
Service: The Forest
Modified: Yes

**Comment by parkervcp** [comment]
So I would say you don't need to install xvfb or anything in the install script.

You need a better run container though.

**Comment by WolfPack30156** [comment]
Thank you for your reply, I'll have another look at the container. 

Anything immediately jumping out at you that needs to be addressed first?

**Comment by parkervcp** [comment]
I haven't dug into anything yet but I have several images in my images repo getting close to what you need I think.

They are all their own branches.

**Comment by parkervcp** [comment]
I will specifically call out this image here - https://github.com/parkervcp/images/tree/ubuntu/wine-xvfb

**Comment by WolfPack30156** [comment]
I tried the image you called out, and I'm getting an error where it isn't seeing the xvfb for some reason. 

I'm still looking into this myself just wish the link for the docker source wasn't 404'ing from the original post from NGLoader

I'm much less familiar with docker images than I am with the other bits. Doing some more research. Thank you for the recommendation, I'll poke around some more.

**Comment by parkervcp** [comment]
I am going to close this out as I don't have a PR related to getting the forest into the repo.
