### ISSUE TITLE
[Egg Request]: ownCloud

### ISSUE THREAD

**Issue by Green-Sickness** [parkervcp/eggs#1406]
### Does this expand an already existing service

No

### Link to a game or software

https://owncloud.com/product/

### Links for the download

https://download.owncloud.org/community/owncloud-complete-20210721.zip

### Links for the install docs

https://doc.owncloud.com/server/10.8/

**Comment by Software-Noob** [comment]
ownCloud is a LEMP stack similar to Pterodactyl. It requires a web server, database, and cache storage (e.g., Apache, Mysql, Redis). 

I'd suggest using their [Docker image ](https://doc.owncloud.com/server/10.8/admin_manual/installation/docker/) with Docker instead of trying to put all of this into Pterodactyl.
