### ISSUE TITLE
[Egg Request]: WoW

### ISSUE THREAD

**Issue by LegacyAngel2K9** [parkervcp/eggs#1502]
### Does this expand an already existing service

No

### Link to a game or software

https://worldofwarcraft.com/

### Links for the download

https://github.com/conan513/SingleCore_TC

### Links for the install docs

https://trinitycore.info/en/install/requirements

**Comment by LegacyAngel2K9** [comment]
So this repository has multiple branches, but 3 are in mind:

WoTLK Expansion = AshamaneCore-dmca
Legion Expansion  = legion-reworked
Battle for Azeroth = AshamaneCore-BFA

Maybe add a variable allowing to choose between "wotlk", "legion" and "bfa"?
Also there are 2 servers within this that needs to be running, the "Authserver" and "Worldserver"

Ports for WoTLK = 3724 and 8085
Ports for Legion and BFA = 1119, 8081, 8085 and 8086

**Comment by parkervcp** [comment]
Yeah naw. I regularly say no to closed source things.

**Comment by LegacyAngel2K9** [comment]
Where is this a closed source if you mind me asking?

**Comment by parkervcp** [comment]
I understand that WoW classic is technically safe but it's a thin line.

**Comment by LegacyAngel2K9** [comment]
could you atleast help me make the egg so i could use it for myself atleast? :D
not so good with this :/

**Comment by dapillc** [comment]
The issue is not with the server software or custom built databases, it's with the data that's required to run the server. You must have a copy of only 3.5.5a, extracted the data from the game client yourself, and upload that data to your server using the freely available tools. Once you extract the data and transfer it to another device, you have now broken the EULA with Blizzard (Reverse Engineering).

I see no issue with creating the egg itself and making it available for others, but testing and verifying the egg is supported would mean you have also broken the EULA with Blizzard. I agree with @parkervcp in saying that it's closed source and that it can never officially be supported.
