### ISSUE TITLE
[Bug]: RedM Typo (fix inside)

### ISSUE THREAD

**Issue by BenasPaulikas** [parkervcp/eggs#1515]
### Panel Version

latest

### Wings Version

latest

### Service

redm

### Modified

No, I did not modify the egg

### Expected Behavior

No error

### Actual Behavior

Running curl -sSL https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/ -o 
curl: option -o: requires parameter
curl: try 'curl --help' or 'curl --manual' for more information

### Steps To Reproduce

```
echo -e "Running curl -sSL ${DOWNLOAD_LINK} -o ${DOWNLOAD_LINK##*/}"
curl -sSL ${DOWNLOAD_LINK} -o ${DOWNLOAD_LINK##*/}
```
Last line should be buggy because it includes "##*/" therefore download link isn't passed.
Last line should be buggy 

### Install logs

above

**Comment by parkervcp** [comment]
`{DOWNLOAD_LINK##*/}` converts a link from `link.url/filename` to `filename`

**Comment by parkervcp** [comment]
If anything you have passed it a bad version.

**Comment by Software-Noob** [comment]
Following the issue template would be useful. The issue is caused by a space in the href that it's grepping for, and it shouldn't even need to grep for href.

Change line 18 to `LATEST_RECOMMENDED=$(echo -e "${RELEASE_PAGE}" | grep "LATEST RECOMMENDED" -B1 | grep -Eo '".*/*.tar.xz"' | grep -Eo '".*"' | sed 's/\"//g' | sed 's/\.\///1')`

Although for the latest, we should use their release API? I'm not around to push a fix.

**Comment by parkervcp** [comment]
Did they add a release api? Last I saw they still didn't have one.

**Comment by Software-Noob** [comment]
> Did they add a release api? Last I saw they still didn't have one.

No, but they have `https://changelogs-live.fivem.net/api/changelog/versions/linux/server` for easy fetching of latest
