### ISSUE TITLE
[Bug]: If you are the server owner, are you sure you are allowing UDP packets to and from the server?

### ISSUE THREAD

**Issue by enricorichardo123** [parkervcp/eggs#1552]
### Panel Version

1.7.0

### Wings Version

1.6.1

### Service

gta fivem

### Modified

No, I did not modify the egg

### Expected Behavior

If you are the server owner, are you sure you are allowing UDP packets to and from the server? 

This is the eror i get when trying to connect to my server (my pterodactly works normal on everything)

### Actual Behavior

If you are the server owner, are you sure you are allowing UDP packets to and from the server?

### Steps To Reproduce

installing egg normally and then creating server and run the server

### Install logs

.

**Comment by parkervcp** [comment]
All servers get tcp and udp allocated with a port. If you allocate 30110 you get 30110/tcp and 30110/udp.

This looks more like your host, firewall, or router are blocking things and not the panel. Several hosts block ports for users because it may overlap with another service they host. ZAP does this with the default fivem ports.
