### ISSUE TITLE
[Egg Request]: Add BepInEx to V Rising egg

### ISSUE THREAD

**Issue by recon88** [parkervcp/eggs#1706]
Can we get the **BepInEx** modloader as an optional setting added to the V Rising egg? 

### Does this expand an already existing service

Yes

### Link to a game or software

https://v-rising.thunderstore.io/package/BepInEx/BepInExPack_V_Rising/

### Links for the download

https://v-rising.thunderstore.io/package/BepInEx/BepInExPack_V_Rising/

### Links for the install docs

https://v-rising.thunderstore.io/package/BepInEx/BepInExPack_V_Rising/

**Comment by recon88** [comment]
Just a little side note if it will be added:
The file **.wine/user.reg** has to be changed.

Add:

`"winhttp"="native,builtin"`

after
```
[Software\\Wine\\DllOverrides] 1654776012
#time=1d87bf879443852
```
Otherwise it will not load BepInEx. This is only an _issue_ with linux/wine

**Comment by lilkingjr1** [comment]
If this functionality cannot be easily turned on or off via a Pterodactyl Startup parameter (which I don't think it can, because files would have to be added, and a whole line added or removed from `.wine/user.reg`), then I feel it would be better as a separate "V Rising (Modded)" egg (like how Valheim is).

**Comment by recon88** [comment]
Adding files shouldn't be an issue I guess since it works for other eggs just fine. Example: Rust + umod
But the line change/addition is required. Not sure if possible, but the egg or image could provide a 2nd file containing the required changes?
If not, then the separate egg would be fine as well.

**Comment by lilkingjr1** [comment]
Rust uses a custom image to help add or remove mod files, and this egg uses the default Wine image (which would not be able to be modified to add this functionality). A custom image *could* be written for V Rising to fulfill this functionality, but I personally have no knowledge or interest in BepInEx, so I would just ask to be removed as a maintainer of the egg if parker thinks this is the best approach (which is fine with me if that's the case). However, separate eggs would, in my opinion, be the easiest and fastest way to get this mod implemented because it would not require a custom image to be written and it would allow the eggs to be maintained separately (which may be important given the bleeding edge nature of the BepInEx framework and a Linux server binary for V Rising potentially coming out soon).
