### ISSUE TITLE
[Egg Request]: Packwiz

### ISSUE THREAD

**Issue by ImUrX** [parkervcp/eggs#1735]
### Does this expand an already existing service

Yes

### Link to a game or software

minecraft.net

### Links for the download

https://github.com/packwiz/packwiz-installer-bootstrap/releases/latest

### Links for the install docs

https://packwiz.infra.link/tutorials/installing/packwiz-installer/

**Comment by ImUrX** [comment]
Packwiz doesnt install the specified server type, so idk whats better. Having multiple packwiz eggs (Fabric, Forge, etc) or just one

**Comment by Software-Noob** [comment]
This appears to be something rather installed part of an existing server and does nothing as a standalone egg.

**Comment by ImUrX** [comment]
Another warning is that since curseforge has added an option for disabling 3rd party API support. The installer will error out when it cant download a certain mod and ask the user to download it and place it in the mods folder

**Comment by ImUrX** [comment]
> This appears to be something rather installed part of an existing server and does nothing as a standalone egg.

I would honestly like this as an option for eggs, you press reinstall and the server updates the modpack. Seems useful enough tbh.
And yes, this isnt an actual minecraft server. It's a modpack manager which is useful, many modpacks actually use it because you can just for example update all mods with just doing ``packwiz update --all`` or install mods and all its dependencies with just ``packwiz cf install mod-name`` and it will warn you when you have incompatible mods.

**Comment by Software-Noob** [comment]
It's a very niche option to install for every user on all the eggs. I'd advise you to modify the install script of your egg to install it.

**Comment by ImUrX** [comment]
Should I make a new issue for modrinth modpack support and fabric generic curseforge support? There is also Quilt being made which is an alternative to Fabric and there are already mods that only support exclusively Quilt

**Comment by Software-Noob** [comment]
We don't currently accept any more new Minecraft-related eggs, since there are a billion variations of them and they only keep on stacking up with no support.

**Comment by ImUrX** [comment]
Is it possible to kind of make your life easier using [this image](https://github.com/itzg/docker-minecraft-server) instead of maintaining every type of minecraft server? I have never made any eggs but I know how to use docker so yeah no idea.

**Comment by Software-Noob** [comment]
Any images that are used by Pterodactyl are managed by us for security, peace of mind, and because Pterodactyl has different requirements compared to normally running Docker/compose, such as entrypoint, rootles, and executing startup args. 

Creating large images with each egg installed inside defeats the purpose of the Panel when we explicitly have eggs for that purpose. Eggs contain the configuration on how each server is created; image, startup args, env variables, and the install container script.

It would also make thousands of users re-download the image each time any change is made to it thus stalling the startup process and wasting disk space/bandwidth, and we have many thousands of monthly downloads on existing images already.

The Docker images only contain the required packages to run them and not the files, which are configured and downloaded by the egg install script. They're versatile and can be updated and modified by anyone easily, compared to Docker images.
