### ISSUE TITLE
[Bug]: CurseForge Better Minecraft failure

### ISSUE THREAD

**Issue by SammesV** [parkervcp/eggs#1737]
### Panel Version

1.4.2

### Wings Version

1.5.3

### Service

minecraft/java/forge/curseforge-generic

### Modified

No, I did not modify the egg

### Expected Behavior

I would like to install an Better Minecraft server with the CurseForge egg. 
https://www.curseforge.com/minecraft/modpacks/better-minecraft-fabric

### Actual Behavior

Server crashed with "Error: Unable to access jarfile server.jar"

### Steps To Reproduce

1. Create new server with Egg, Project ID, API key
2. Server installed
3. Installation completed with the following errors in the console
- "Installing forge server using the installer jar file. No forge installer found moving on."
- "mv: cannot stat 'forge*.jar': No such file or directory"

4. When I try to start the server "Error: Unable to access jarfile server.jar" is displayed

### Install logs

https://www.toptal.com/developers/hastebin/ufujufedat.yaml

**Comment by QuintenQVD0** [comment]
Can confirm on latest panel and wings!

**Comment by Software-Noob** [comment]
The modpack doesn't ship the jar required to run it. The egg can't handle every possible type of modpacks, since there are way too many of them with each having a different setup and no time or interest to cover them all.  Most of them nowadays ship only the mods and have seperate shellscripts that download installers and Minecraft jars.

Manual intervention might be required for those that it can't install - it can however pull the files and it will try to run installers if one exists.

**Comment by harveydobson** [comment]
So I have the same issue, and in the container all i can see is a single `server.properties`, no sign of any other files being pulled from CurseForge. Is this normal? 

I've also tried running `ls -al` as the start-up command and can confirm the same is present in the logs at the time that it would be running a startup script.

**Comment by Crumb5** [comment]
Can confirm this for me as well. 
I notice on server install:
```
container@pterodactyl~ Starting installation process, this could take a few minutes...
Installing required packages...
        Running apt update
        Running apt install
Retrieving CurseForge project information...
        ERROR: Failed to retrieve project data for project id '715572'
```
