### ISSUE TITLE
Add flexify.io

### ISSUE THREAD

**Issue by r3in3r** [parkervcp/eggs#1822]
### Does this expand an already existing service

No

### Link to a game or software

https://flexify.io/

### Links for the download

https://hub.docker.com/r/flexifyio/ce

### Links for the install docs

https://hub.docker.com/r/flexifyio/ce

**Comment by Software-Noob** [comment]
You didn't provide any installation documentation for the software itself nor am I able to find anything on their public documentation, which contains only 3 articles.

Existing Docker images are not useful as Pterodactyl is not Portainer or docker-compose that runs them. The linked image source is also private.

Feel free to open a new request once you can provide proper install instructions on hardware for us to review and follow. Otherwise, use Docker itself with the provided image.
