### ISSUE TITLE
[Bug]: Satisfactory Egg: Refusing to run with the root privileges

### ISSUE THREAD

**Issue by dustin-ha** [parkervcp/eggs#1858]
### Panel Version

1.10

### Wings Version

1.7.0

### Service

Satisfactory

### Modified

No, I did not modify the egg

### Expected Behavior

Install update from SteamCMD and start the Server.

For background: Im running the wing Agent on a LXC on proxmox, nesting enabled, with no problems yet. Already running different Minecraft Servers (Forge, FTB, Vanilla) and a Rust Server without any Problems.

### Actual Behavior

Right after the start command the Error message `Refusing to run with the root privileges` shows,and the Server stops

### Steps To Reproduce

1. Import the Satisfactory egg
2. Create a Standard Server (using Standard Ports and all Standard Scripts)
3. After the installation (successfull) start the Server
4. Wait for the Start Command after the Updates was installed

### Install logs

https://pteropaste.com/fxr3et

**Comment by gOOvER** [comment]
I never had this error message and LXC is not a supported VM

**Comment by lilkingjr1** [comment]
You need to ensure the container is not being started with root privileges in your specialized environment. Unreal Engine servers (which Satisfactory uses) do not allow them to be run with root privileges for security reasons. Nonetheless, this issue is not egg related; the blame can either be placed on your container configuration or how the Satisfactory server is compiled.
