### ISSUE TITLE
Link to cod4x on homepage of github is broken.

### ISSUE THREAD

**Issue by Crush3rX** [parkervcp/eggs#2165]
### Does this expand an already existing service

Yes

### Link to a game or software

cod4x

### Links for the download

none

### Links for the install docs

none

**Comment by gOOvER** [comment]
cod4x was removed, because its against ToS

**Comment by grimsi** [comment]
> cod4x was removed, because its against ToS

Hey there. Sorry for re-opening this old issue but I just noticed that my CoD4X egg got removed.
Can you elaborate on how this is against your terms of service? As far as I know you need to have an original copy of CoD4 in order to play this mod.

**Comment by parkervcp** [comment]
> against your terms of service

I don't have a terms of service for the repo. I would rather avoid any server that isn't either publicly available or via some sort of tool/api like steamcmd.

Reading back through the PR's it was removed because their domain expired and anyone could have uploaded a virus to their domain. With the knowledge that there is a github for it someone can PR an updated egg using github.
