### ISSUE TITLE
Error on installing FiveM server

### ISSUE THREAD

**Issue by mateusjose** [parkervcp/eggs#233]
Please fill out the information bellow and remove from the line up
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 0.7.14
Daemon Version: 0.6.12
Service: FiveM
Modified: no
Expected Behavior: After Install start the FiveM server

Actual Behavior: Error on try to start FiveM server
:/home/container$ /home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path /home/container/alpine/usr/lib/v8/:/home/container/alpine/lib/:/home/container/alpine/usr/lib/ -- /home/container/alpine/opt/cfx-server/FXServer +set citizen_dir /home/container/alpine/opt/cfx-server/citizen/ +set sv_licenseKey uoxo9a2ebd3rvewt8piibsv0rs4ts1ea +set sv_maxplayers 32 +exec server.cfg
/entrypoint.sh: eval: line 1: /home/container/alpine/opt/cfx-server/ld-musl-x86_64.so.1: not found

Steps to Reproduce: Create a server for FiveM

**Comment by parkervcp** [comment]
You are missing files. I need to see the install logs.

**Comment by mateusjose** [comment]
The log directory is empty in both of my test servers

**Comment by Kudjoch** [comment]
I have the same problem started today.

**Comment by Nexxed** [comment]
The issue seems to be with the part where the installation script tries to find the latest version, but it can't so it downloads an invalid file from the FiveM runtime archive, resulting in a failed installation.

Here is a simple and quick fix for this, though keep in mind that if/when @parkervcp updates the egg, it's best for you to update your install script with the new one since it'll likely have support for automatically grabbing the latest artifact.
```bash
#!/bin/ash 

apk add openssl tar xz curl wget git --no-cache

cd /mnt/server

mkdir resources

echo "updating citizenfx resource files"
git clone https://github.com/citizenfx/cfx-server-data.git /tmp
cp -Rf /tmp/resources/* resources/ 

cd /mnt/server

echo "Downloading the FiveM server files for artifact #1380"
wget https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/1380-0b3915618c6cc278c2457ea93775255ed41e49c3/fx.tar.xz

echo "Extracting fivem files"

tar xf fx.tar.xz

rm -rf fx.tar.xz run.sh

if [ -e server.cfg ]; then
    echo "server config file exists"
else
    echo "Downloading default fivem config"
    curl https://raw.githubusercontent.com/parkervcp/eggs/master/gta/fivem/server.cfg >> server.cfg
fi

mkdir logs/

echo "install complete"```
To apply this fix, just open your egg in the Pterodactyl panel and head over to the Scripts tab, where you'll find the install script. Replace the install script in the egg with the one above and reinstall your server(s).

**Comment by mateusjose** [comment]
@Nexxed this solution work for me, thanks.
