### ISSUE TITLE
[Bug]: <all eggs>

### ISSUE THREAD

**Issue by Beansavery** [parkervcp/eggs#2848]
### Panel Version

1.11.5

### Wings Version

unsure

### Service

pterodactyl

### Modified

No, I did not modify the egg

### Expected Behavior

import eggs json file, egg is then imported

### Actual Behavior

error after selecting import
There was an error validating the data provided.

The import file failed to upload.

### Steps To Reproduce

step 1 import egg
step 2 select json file
step 3 fails to import
![image](https://github.com/parkervcp/eggs/assets/137006107/d53919d2-4bdf-4f4a-9148-14263cf6f9fd)

### Install logs

N/A

**Comment by gOOvER** [comment]
works fine

you Download the Egg in a wrong way

**Comment by lilkingjr1** [comment]
This is user error and not an issue with the eggs. It seems you are downloading the wrong thing, or the egg file you are trying to import is corrupted. Also, make sure your panel is up to date. This issue will be closed, but feel free to continue to ask for further support here with a reply or on the Discord.

**Comment by Darkcarnage23** [comment]
Sorry for unwanted comment/spam if you consider this.  I came across this while searching

This issue **may** occur if you're a caddy user.  You need to modify the CaddyFile as shown [here](https://github.com/pterodactyl/documentation/pull/575/files)

Other time it's usually because the egg you're importing is corrupted, or you tried to edit it via file which somehow broke it.  It's likely the above
