### ISSUE TITLE
FiveM oNe sync / Override 32 slots

### ISSUE THREAD

**Issue by Deiity** [parkervcp/eggs#299]
Hi,

I can't change in egg FiveM limit of slot to 32, now its 31. Also, you can't enable onesync and can't override 31 slot limit, can you advise how to do that? Thanks.

**Comment by parkervcp** [comment]
OneSync is in beta last I checked and I will not support it. https://forum.fivem.net/t/the-onesync-eap-and-you/165931

in their words - "Linux is still not considered supported. It might work, but because there’s no tracing/error reporting functionality, you won’t receive any support, and will experience issues."

Recent changes the fivem team have made also break the current egg.

**Comment by Deiity** [comment]
Hi, i understand that, but what about slots? Can i put 32 slots manually atleast? Currently its 31 slot and can't override it.

**Comment by parkervcp** [comment]
Max players is managed at the egg level. You can update that in the nest.

**Comment by parkervcp** [comment]
This could have been handled in discord. Closing out.
