### ISSUE TITLE
Farming Simulator 2019

### ISSUE THREAD

**Issue by baxandrei** [parkervcp/eggs#307]
Service: Farming Simulator 2019

Does this expand an already existing service: Yes (Unturned)

Link to game: https://store.steampowered.com/app/787860/Farming_Simulator_19/

Links for server downloads: dedicatedServer.exe (will be downloaded with game).

Links for install steps/docs: Only exec dedicatedServer.exe.

**Comment by YeapGuy** [comment]
Would love to see this +1

**Comment by parkervcp** [comment]
How is this expanding on Unturned?

**Comment by baxandrei** [comment]
Because uses same method of server start using mono.

I will try to install it on a test linux machine with steamcmd to ensure that it works.

**Comment by YeapGuy** [comment]
@baxandrei Yeah, FS19 only officially supports Windows servers, but there are ways to run it on Linux, using Wine.

**Comment by parkervcp** [comment]
Just because it starts the same way doesn't mean it expands on the other service...

**Comment by baxandrei** [comment]
Ok, my bad. sorry..

**Comment by YeapGuy** [comment]
Any updates? (also, you might want to add the "egg request" tag)

**Comment by parkervcp** [comment]
I am closing this out. I don't want to fight with wine to try and get it working. 

If someone can get a working copy of the server to run in wine, and join it, I will consider accepting a PR.

**Comment by PanGeo-Code** [comment]
Hello, I know that what i'm about to post isnt going to work on pterodactyl because this has been told by the support of pt discord But i have goten this to work with Docker

Webpanel WORKS
And i have goten the farming Server to startup there were still a few problems with renaming the server name and maps mods enzv but i do not have that big of a Knowledge about this whole thing.

Github: https://github.com/smearieryeti/docker-farming-simulator-server#wip
