### ISSUE TITLE
Pavlov VR Game Request

### ISSUE THREAD

**Issue by TonyS95** [parkervcp/eggs#481]
Service: Pavlov VR  (saw someone comment on the eggs channel about wanting it)

Does this expand an already existing service: Y/N

Link to game: https://store.steampowered.com/app/555160/Pavlov_VR/

Links for server downloads: You can do it via steamcmd

Links for install steps/docs: http://wiki.pavlov-vr.com/index.php?title=Dedicated_server

**Comment by TASelwyn** [comment]
https://github.com/TASelwyn/eggs/tree/add/pavlov/steamcmd_servers/pavlov_vr

Worked on one a bit, it installs, launches then upon starting it seems to start fine, then sits there spamming:

[2020.12.07-19.03.06:139][205]PavlovLog: Sending heartbeat to masterserver

No idea if you can connect as I have not tried but seems to start just fine.
I'm not sure how console termination is meant to work, the guide says to "just close the terminal" and the server will stop, but it seems to stop around 30s after the stop button is pressed. Likely due to a wrong stop termination command (giving ^C currently)

**Comment by smishcraft** [comment]
I will look at working on this as well as I would also like a working pavlov egg.

**Comment by smishcraft** [comment]
I span up the independent version and the egg, the console spam is normal by the looks of things. In regards to the stop command I found NOTHING other than ^C works and no other commands are documented anywhere, (tested with both egg and independent).

Other than slight change to the start up command to make it viable for a shared hosting environment/multi-instance install the egg works as it should.

Will fork main repo and upload slight changed version with credits.

**Comment by TASelwyn** [comment]
> I span up the independent version and the egg, the console spam is normal by the looks of things. In regards to the stop command I found NOTHING other than ^C works and no other commands are documented anywhere, (tested with both egg and independent).
> 
> Other than slight change to the start up command to make it viable for a shared hosting environment/multi-instance install the egg works as it should.
> 
> Will fork main repo and upload slight changed version with credits.

you can always pr my repo for simplicity

**Comment by smishcraft** [comment]
> 
> you can always pr my repo for simplicity

Didn't think about that :/ Already forked and PR'ed it.

**Comment by TASelwyn** [comment]
> > you can always pr my repo for simplicity
> 
> Didn't think about that :/ Already forked and PR'ed it.

and you spelt my name wrong :wazowski_stare:

**Comment by smishcraft** [comment]
Removed my PR so @TASelwyn can PR it as I made a few mistakes in mine. Lessons learned for next time.
