### ISSUE TITLE
Discord bot egg: Red - Failed downloading lavalink.jar

### ISSUE THREAD

**Issue by NanoNode** [parkervcp/eggs#550]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: Latest
Daemon Version: Latest
Service: Redbot - Egg
Modified: no

Expected Behavior:
when running $load audio it was supposed to download the lavalink to enable the music functionality.
Actual Behavior:
Error'd
Steps to Reproduce: 

1. Input your token and prefix.
2. Start redbot instance via panel.
3. Invite the bot to discord server.
4. Load the audio cog.
5. Check console for error.

https://hastebin.com/apomutocih.cs

The error I got was " OSError: [Errno 28] No space left on device " when there is plenty of space left on the machine and the node has a lot more space allocated too it.

**Comment by iamkubi** [comment]
This happens when you don't have enough space on /tmp.  You need to increase the size by changing the `tmpfs` setting as documented here:
https://pterodactyl.io/daemon/0.6/configuration.html#container-policy

I'll resolve this issue by updating the README to indicate this is necessary, assuming it's not already documented there.
