### ISSUE TITLE
Vanilla Terraria: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Endoman123** [parkervcp/eggs#577]
Panel Version: 0.7.17
Daemon Version: 0.6.13
Service: Terraria
Modified: no

Expected Behavior: Server should just start

Actual Behavior: Server crashes w/ error trace:
```
System.NullReferenceException: Object reference not set to an instance of an object
at Terraria.Main.WriteFancyWorldLoadErrorToConsole () [0x00005] in <0ebea07e9a804a06a9f1dd17904b9c9c>:0
at Terraria.Main.DedServ () [0x00b21] in <0ebea07e9a804a06a9f1dd17904b9c9c>:0
at Terraria.Program.LaunchGame (System.String[] args, System.Boolean monoArgs) [0x000ac] in <0ebea07e9a804a06a9f1dd17904b9c9c>:0
```

Steps to Reproduce:
1. Install Terraria Egg
2. Create new Terraria Server
3. Start server

**Comment by iamkubi** [comment]
There's a bug in Terraria 1.0.5, it doesn't run on Linux.  There's a pinned message in the #eggs channel in Discord that has a fix.  I don't plan on adding this to the egg because it's a hack that should only be required for 1.4.0.5, unless they create a new release without fixing the known issue.

https://forums.terraria.org/index.php?threads/terraria-server-1-4-0-5-world-generation-crash.93411/post-1989953
