### ISSUE TITLE
Dead Matter egg

### ISSUE THREAD

**Issue by iamkubi** [parkervcp/eggs#651]
Service: Dead Matter
Does this expand an already existing service: N
Link to game: https://qisoftware.ca/

Links for server downloads: Server files are not released yet.

Links for install steps/docs:
Not released yet.  From what I've gathered there will only be Windows support when they launch their closed alpha next week, but a Linux server is planned.  Depending on what I hear back from their team I'll likely [try to] make an egg using wine for this to start out with and transition it to use the Linux server once it's released.

**Comment by 60plus** [comment]
Hi. 
Any luck with this egg ? Or it has been abandoned ?

**Comment by gOOvER** [comment]
can be closed; since 2 years its Not possible to buy this Game

**Comment by QuintenQVD0** [comment]
I will close this for now. If there game ever releases and has a dedicated server and instructions to set it up. Then this can be reopend

**Comment by coyottetv** [comment]
helo with the new update the egg still works?

**Comment by gOOvER** [comment]
> hello with the new update the egg still works?

noone can test, becasue noone can buy this game ;) so test it, then you see

**Comment by coyottetv** [comment]
noone can test, becasue noone can buy this game ;) so test it, then you see

I just tested Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
Success! App '2584780' already up to date. 

it works just one problem  proton run  /home/container/DeadMatter/Binaries/Win64/DeadMatterServer-Win64-Test.exe -log

LogSteamShared: Display: Loading Steam SDK 1.53
LogSteamShared: Warning: Steam Dedicated Server API failed to initialize.
LogOnline: Warning: STEAM: Failed to initialize Steam, this could be due to a St
eam server and client running on the same machine. Try running with -NOSTEAM on
the cmdline to disable.

when I remove -log the server gives an idea of the problem
