### ISSUE TITLE
Having a few troubles with the Ark egg

### ISSUE THREAD

**Issue by Darciah** [parkervcp/eggs#83]
Panel Version: 0.7.10
Daemon Version: Unsure, but can find out from server admin if this is critical
Service: Ark: Survival Evolved
Modified: No. We are using the latest version of the egg.

Expected Behaviour: using the -automanagemods switch on the startup command should allow Ark to retrieve mods from the steam workshop thus allowing for mods to keep updated as per Ark updates.

Actual Behaviour: using the -automanagemods switch in the startup string causes the server initiation to stall and be marked as 'killed'. The server then attempts to auto restart and the mods (folders) and not updated and the accompanying .mod files are deleted from the Mods folder.

Steps to Reproduce: Upon successfully installing the Ark server, ensuring all the relevant ports are added. We then specify Mod# in the game.ini under [Managed_Mods] and then add the -automanagemods to the startup string on Pterodactyl and start the server as normal. Ark will attempt to check for updates via SteamCMD (which it successfully does) and will also attempt to grab mods from Steam Workshop (which it tries to, but fails). Mods are not installed, but Ark starts anyway.

Excerpt from console:
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 9218M / 120000M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Server marked as KILLED.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Success! App '376030' already up to date.
[Pterodactyl Daemon] Server marked as STARTING
:/home/container$ ./ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?listen?ServerPassword=******?ServerAdminPassword=******?Port=7777?MaxPlayers=20?QueryPort=27015?RCONPort=27020 -ForceAllowCaveFlyers -ForceRespawnDinos -automanagedmods
Using binned.
4.5.1-0+UE4 7038 3077 403 10
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
[Pterodactyl Daemon] Server marked as ON
[Pterodactyl Daemon] Server marked as STOPPING
quit

**Comment by parkervcp** [comment]
We don't use automanagedmods by default and I don't use them at all. Do you have an example of this kind of set up that I can replicate?

**Comment by Darciah** [comment]
Well, with our Ark server setup, we use a number of mods. Under server config and looking at the startup command on Pterodactyl, if you use "./ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?listen?ServerPassword={{ARK_PASSWORD}}?ServerAdminPassword={{ARK_ADMIN_PASSWORD}}?Port=7777?MaxPlayers=20?QueryPort=27015?RCONPort=27020"and adding -automanagedmods, this should tell the server to check for mod updates. Steps to reproduce:
Before adding the switch, setup a none-modded game and then add the following to game.ini within the saved config directory:

[ModInstaller]
ModIDS=1342813568
ModIDS=821530042
ModIDS=566887000
ModIDS=630601751
ModIDS=731604991
ModIDS=566885854
ModIDS=793605978
ModIDS=812655342

Then in the gameusersettings.ini in the same directory, add:

[ServerSettings]
ActiveMods=1342813568,821530042,566887000,630601751,731604991,566885854,793605978,812655342

With -automanagedmods in your startup command, the normal behaviour up on start, would be that it would seek out the mods you've specified and install/update them under "/home/container/ShooterGame/Content/Mods"

You should see a number of folders and .mod files that correspond to the ModIDs.

Ark, itself, does check for updates to Ark via SteamCMD, but as I said, the -automanagedmods function does not appear to function as it should or, indeed, is not present.

The only way as of typing this is to manually upload mods as they are updated to reflect Ark's version number. Since we are a relatively small modded server, the uploads (compressed) start at 250Mb. I expect that more heavily modded servers using this manual setup could be getting on for a gig or two. This is what prompted me to reach out to you and to see if there would be a potential solution to the automated feature.

**Comment by parkervcp** [comment]
Many things I saw stated to not use autmanagedmod in linux. We have steamcmd in the files but I am not sure if ark sees it.

**Comment by SheppeR** [comment]
the problem is simple, 
1: SteamCMDInstall.sh should be executed 1 time for install required steamcmd files for mods (required for internal server process)

2: We have to symlink  deamon-data/xxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/Steam/steamapps to  deamon-data/xxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps

3: The server is started from ARK root path like ./ShooterGame/Binaries/Linux/ShooterGameServer by default. This will not work for install mods.

To fix the problem, we should move into bin folder in first time like:
cd deamon-data/xxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/ShooterGame/Binaries/Linux/
and then start the server
./ShooterGameServer TheIsland?listen?ServerPassword....

**Comment by IdefixRC** [comment]
Hi guys, quick check whether this is working now? I'm looking into deploying the Pterodactyl ARK Server and would need the mods (using LinuxGSM at the moment and it works fine here with -autmanagedmod

Thanks

**Comment by IdefixRC** [comment]
Answering my own question: with mod IDs added to game.ini and gameusersettings.ini (same config I used for my LinuxGSM server before), the server starts flawlessly, downloads and installs all mods. Happy days :-)

**Comment by marci2oo9** [comment]
Hey , this script will work for me , but when i put mods in the gameusersettings.ini and start the server it will download the mods and start the server but i can not connect , because the server says me outdated mods.

Console says:
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[ 0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Update state (0x61) downloading, progress: 1.24 (5100544 / 411313152)
completionportmanager_posix.cpp (356) : Assertion Failed: Async I/O on closed handle 98
completionportmanager_posix.cpp (356) : Assertion Failed: Async I/O on closed handle 99
completionportmanager_posix.cpp (356) : Assertion Failed: Async I/O on closed handle 100
completionportmanager_posix.cpp (356) : Assertion Failed: Async I/O on closed handle 101
completionportmanager_posix.cpp (356) : Assertion Failed: Async I/O on closed handle 102
completionportmanager_posix.cpp (356) : Assertion Failed: Async I/O on closed handle 103
completionportmanager_posix.cpp (356) : Assertion Failed: Async I/O on closed handle 104
completionportmanager_posix.cpp (356) : Assertion Failed: Async I/O on closed handle 105
assert_20200201174537_34.dmp[57]: Uploading dump (out-of-process)
/tmp/dumps/assert_20200201174537_34.dmp
Update state (0x61) downloading, progress: 57.10 (234861568 / 411313152)
assert_20200201174537_34.dmp[57]: Finished uploading minidump (out-of-process): success = yes
assert_20200201174537_34.dmp[57]: response: Discarded=1
assert_20200201174537_34.dmp[57]: file ''/tmp/dumps/assert_20200201174537_34.dmp'', upload yes: ''Discarded=1''
Success! App '376030' fully installed.
:/home/container$ cd ShooterGame/Binaries/Linux && ./ShooterGameServer Valguero_P?listen?SessionName='ArkServer2 by Mysterygaming.de'?ServerPassword=?ServerAdminPassword=?Port=7777?RCONPort=27020?QueryPort=27015?RCONEnabled=false?MaxPlayers=10 -server -log
Using binned.
4.5.1-0+UE4 7038 3077 404 10
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
[ 0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Downloading item 902548451 ...
Success. Downloaded item 902548451 to "/home/container/Steam/steamapps/workshop/content/346110/902548451" (470296717 bytes) Downloading item 880871931 ...
Success. Downloaded item 880871931 to "/home/container/Steam/steamapps/workshop/content/346110/880871931" (333126911 bytes) Downloading item 1211297684 ...
Success. Downloaded item 1211297684 to "/home/container/Steam/steamapps/workshop/content/346110/1211297684" (249994594 bytes) Downloading item 849372965 ...
Success. Downloaded item 849372965 to "/home/container/Steam/steamapps/workshop/content/346110/849372965" (57022119 bytes) Downloading item 741203089 ...
Success. Downloaded item 741203089 to "/home/container/Steam/steamapps/workshop/content/346110/741203089" (440482359 bytes) Downloading item 1786522940 ...
Success. Downloaded item 1786522940 to "/home/container/Steam/steamapps/workshop/content/346110/1786522940" (437487 bytes) Downloading item 731604991 ...
Success. Downloaded item 731604991 to "/home/container/Steam/steamapps/workshop/content/346110/731604991" (41692077 bytes) Downloading item 793605978 ...
Success. Downloaded item 793605978 to "/home/container/Steam/steamapps/workshop/content/346110/793605978" (415537 bytes)



i think the folder for the mods is not correctly.

**Comment by chaoschao11** [comment]
I have found a workaround of sorts for how to get mods on the ark server. It's pretty simple, the main part is that you don't use SteamCMD to get the mods:

1. Download the mod you want via the steam workshop to your ark client
2. Navigate to your local ark files, for C:\Program Files (x86)\Steam\steamapps\common\ARK
3. Go to your mods folder [Steam Install Directory]\steamapps\common\ARK\ShooterGame\Content\Mods
4. Make a copy of the mod folder and the accompanying .mod file. Make a note of the ModID.
5. Paste the mod folder and accompanying .mod file into the servers /ark-survival-evolved/ShooterGame/Content/Mods 
6. Start the server, let it load fully, and then stop the server
7. Navigate to the /ark-survival-evolved/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini file on the server
8. Under the **[ServerSettings]** heading, you will need to add a new line with this entry: ActiveMods=
9. After the ActiveMods= entry, you must list every ModID for every mod that you want to load in your mods folder. The order doesn't matter. If you have more than one mod, the ModIDs must be separated with a comma like this: ActiveMods=xxx,xxx,xxx

That worked for me! So hopefully it helps everyone else, (I'll try and add some photos for reference later)

**Comment by parkervcp** [comment]
I think I may try out adding a symlink for the mods folders

**Comment by SheppeR** [comment]
The current egg on repo already symlink the mod folder, the egg work just fine, user just have to edit game.ini (allow to downlaod mods from workshop)  and GameUserSettings.ini(load mod on server)
