### ISSUE TITLE
Arma 3 Egg update makes server unable to start

### ISSUE THREAD

**Issue by Thadah** [parkervcp/eggs#950]
# If you are seeing any of the following go to Discord and port your error in a support channel.
  * `A fatal error was encountered while starting this server.`
  * `No server egg configuration could be located; aborting startup.`

Please fill out the information bellow and remove from the line up  
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 1.2.2
Daemon Version: 1.2.2
Service: Arma 3
Modified: yes

Expected Behavior:
The server to start after the container update probably triggered by https://github.com/parkervcp/eggs/pull/948

Actual Behavior:
The server tries to start but doesn't find the binary file that is clearly there and with the right permissions set.

```container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/pterodactyl-images 
Digest: sha256:635b0fbe003793d59fba3acc91627ace25a5e7fea84744896b7cef1d51d4edf8 
Status: Image is up to date for quay.io/parkervcp/pterodactyl-images:game_arma3 
[Pterodactyl Daemon]: Finished pulling Docker container image

STARTUP_ERR: Specified server binary could not be found in files! Verify your Server Binary startup variable.
container@pterodactyl~ Server marked as offline...
```

Creating a new server also shows the same exact behaviour

Steps to Reproduce: (Step by step what to do to cause the issue)
Restart the server with the old egg, triggering the egg update and causing the issue

**Comment by lilkingjr1** [comment]
As you said in your Steps to Reproduce, you tried booting the server with the old egg. The old (defunct) egg downloads from the same image URL, which as since been [updated](https://github.com/parkervcp/images/pull/70) with new variables that the old egg does not provide. Therefore, the new image startup script complains that the old egg is missing the server binary file variable.

Granted, I should have had the image fail-safe to the default binary name if the variable is missing (which I will try to fix soon), but for now, updating your egg should be the better solution.

**Comment by Thadah** [comment]
You're right, the egg was outdated. I thought it was autoupdated but only the image was. Updating the egg manually solved the problem. Thanks for the help!

**Comment by gOOvER** [comment]
> You're right, the egg was outdated. I thought it was autoupdated but only the image was. Updating the egg manually solved the problem. Thanks for the help!

There is NO Autoupdating for Egg :)
